### ISSUE TITLE
Literature Review

### ISSUE THREAD

**Issue by cleebp** [cleebp/csc-510-group-g#1]
To justify our development of a clipboard manager we need to either create and test a user group (12 hour rule), or complete a literature review on our topic which justifies our software. 

This can be a place where we keep track of promising literature related to clipboard managers, copy and paste habits, code cloning, etc.

**Comment by arjunmadan** [comment]
Here are a couple of useful papers:

Revealing the Copy and Paste Habits of End Users - 
http://ieeexplore.ieee.org.prox.lib.ncsu.edu/stamp/stamp.jsp?tp=&arnumber=5295296
Managing Code Clones Using Dynamic Change Tracking and Resolution - http://ieeexplore.ieee.org.prox.lib.ncsu.edu/stamp/stamp.jsp?tp=&arnumber=5306336

**Comment by reachspirit** [comment]
Here are some papers on code cloning. It turns out that code clone is quite different from our goal of an efficient clipboard manager. 
Clone management: Clone analysis tool with tag cloud visualization. Jump to the picture. It gives a description of the procedure of clone management.
http://sel.ist.osaka-u.ac.jp/lab-db/betuzuri/archive/962/962.pdf
Another paper on clone management. 
http://www.cs.usask.ca/~croy/papers/2011/Zibran_IWSC2011_Management.pdf
But these papers may help us understand cloning itself better. Although that's quite beyond the scope of this project, we know that we can do more with the clipboard.

**Comment by effat** [comment]
A study of copy and pasting habits in OOP programmars.
http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1334896

**Comment by cleebp** [comment]
Paper on Code Clone Genealogies (cited by 396, from 2005) that proposes that its not always best to immediately refactor code clones, because instead they will either work themselves out eventually, or they are actually pretty necessary.
http://web.cs.ucla.edu/~miryung/Publications/esecfse05-clonegenealogy.pdf 

Paper on 'A study of developer work habits'. (Cited by 367, from 2006) Section 5.4 and Table 3 specifically talk about 6 different types of code duplication (including copy and pasting) and have survey/interviews with developers on each of these times - interesting read and opens up other possibilities to consider for our plug-in, plus this was study based.
https://cs.gmu.edu/~tlatoza/papers/icse2006.pdf 

Another term I'm finding that could be worth investigating is 'Code Duplication' (covers more than just copy and pasting so we may get a different result of papers).

**Comment by arjunmadan** [comment]
Paper on Reverse Engineering Design Patterns in Java (cited by 188, from 2006): 
There are a few common design patterns which are the "best practices" to follow while coding. It's possible this would be out of scope for the extension, but something to consider is detecting whether code being pasted is one of these design patters. The paper talks about detecting these patterns.
http://web.cs.ucdavis.edu/~shini/research/pinot/reverseJavaPatterns.pdf

**Comment by reachspirit** [comment]
Revealing the copy and paste habits of end users (cited by 11, from 2009):
Specific talks on copy and paste habits of end users with a clipboard. By logging interactions while performing everyday tasks, the paper reveals some patterns related to copy and paste. 
http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=5295296&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D5295296

Copy-and-paste between overlapping windows (cited by 28, since 2007):
Window management technique that facilitate copy and paste in the particular case of partially overlapping windows.
http://dl.acm.org/citation.cfm?id=1240657

Smarter cut-and-paste for programming text editors (cited by 14, since 2001):
Discussion on how to improve cut and paste within text editor for programming. Give a prototype tool for better cut and paste practice.
http://dl.acm.org/citation.cfm?id=545654
