### ISSUE TITLE
Exploration with Sublime Platform

### ISSUE THREAD

**Issue by reachspirit** [cleebp/csc-510-group-g#13]
Post supporting materials for Sublime here.

**Comment by cleebp** [comment]
Moving over the links to those 3 sublime clipboard managers here...

Clipboard Manager = https://packagecontrol.io/packages/Clipboard%20Manager
Clipboard History = https://packagecontrol.io/packages/Clipboard%20History
Jimbly's Clipboard History = https://packagecontrol.io/packages/Jimbly's%20Clipboard%20History

**Comment by cleebp** [comment]
Here are my thoughts on the ['Clipboard Manager'](https://packagecontrol.io/packages/Clipboard%20Manager) plugin.

Install isn't too bad, you have to re-register your ctrl-c/ctrl-p (or for mac cmd-c/cmd-p) commands to use the managers commands. Once you are using their copies and pastes however it performs just like normal copy and paste; however, you can choose to show your history at the bottom of the screen like so:

![screen shot 2016-02-09 at 11 47 21 am](https://cloud.githubusercontent.com/assets/3922117/12923245/fe09324c-cf22-11e5-8266-5f4126ec303f.png)

As you can see in the screenshot it handles indents through a special backslash, so while you can just fast copy from this box at the bottom if you want to preserve indents you must use their special commands for traversing the history and paste from that (an inconvenience). You can see where the history is currently pointed at from the big arrow on line 1.

Overall the plugin is nice but I don't like how it goes as far as to add a visual GUI component but you can only interact with it correctly through commands. This may be a larger problem with Sublime extensions on the whole though.

**Comment by cleebp** [comment]
Here are my thoughts on the ['Clipboard History'](https://packagecontrol.io/packages/Clipboard%20History) plugin.

Install is way easier, don't have to remap commands it just works with your native ctrl-c/ctrl-v (or cmd-c/cmd-v) which is nice. Basically as you copy your history is build and by using a complex command (⌘⎇⌃V on mac) you can show your history and it appears in the command box at the top like so:

![screen shot 2016-02-09 at 11 55 27 am](https://cloud.githubusercontent.com/assets/3922117/12923564/37b4404e-cf24-11e5-882f-e7fde47a60dd.png)

From here you can simply click an item and it will show up at your cursor location. Alternatively like the other plug-in you can use commands to navigate the history so your next paste pastes from the current  index. Unlike the other plugin your history doesn't stay visible as you work so you have to enter the command to see the history, then use commands to navigate and paste which is a huge pain.

**Comment by cleebp** [comment]
Here are my thoughts on the ['Jimbly's Clipboard History'](https://packagecontrol.io/packages/Jimbly's%20Clipboard%20History) plugin.

So this just seems like a more updated version of the ['Clipboard History'](https://packagecontrol.io/packages/Clipboard%20History) plugin with an easier command to access the clipboard history. But seriously besides that it seems identical on the surface level:

![screen shot 2016-02-09 at 12 04 34 pm](https://cloud.githubusercontent.com/assets/3922117/12923884/74bf74e4-cf25-11e5-8058-ce40b9c8555e.png)

Its last update was 8 months ago compared to the other plugins last update 3 years ago so really it just seems like the same project with a couple more recent tweaks. Same problem as before with the history not being static.

This is probably our best bet to start working from if we choose to go down the sublime route, my immediate changes to consider making would be:
- Making the history static, in other words have the history always be an active window, right now when you perform any action the history disappears 
- Having the history show automatically after first copy/paste
- Allow dragging from the history rather than just clicking to paste at cursor
- Provide contextual options on the history options, i.e. right-click on the item gives you options to delete it, favorite it, etc.
- Perhaps new display options with more context on where the item came from
- Flag items in the history as 'stickies' or 'favorites' so that they don't disappear
- add contextual options to the history window itself, i.e. right click on the window and there is an option to clear all non favorite items etc.

**Comment by arjunmadan** [comment]
Found this online:
API docs for developing with Sublime. They have something called a 'panel'. Not too sure what it is though. Will explore further later.

https://www.sublimetext.com/docs/3/api_reference.html
