### ISSUE TITLE
Posts on data persistence

### ISSUE THREAD

**Issue by reachspirit** [cleebp/csc-510-group-g#38]
Adding favorite reservations requires persistent data support. There are basically two ways: Using the serialize method provided by atom API or read and write to a file. Post supporting materials here.

**Comment by reachspirit** [comment]
I've been looking for methods of data persistence. The serialize method provided by atom applies typically to classes, while we need to store a global variable history in our case. 

https://www.npmjs.com/package/jsonfile

This package provides a way to read from and write to JSON, but I don't know whether it works with local files, for a browser would forbid cross domain access.

**Comment by arjunmadan** [comment]
Definitely possible to use this. You can write to the file when Atom closes, or even when you copy/cut and then read from it when Atom opens again or initializes.

You might want to take a look at https://nodejs.org/api/fs.html as well. It's what I'm using for the telemetry part so if you take a look at the code I've added to the telemetry, you should have an example on how to implement reading/writing to a file.

**Comment by arjunmadan** [comment]
How'd you implement it would be:
1. Add the package to package.json and then run apm install.
2. Add `fs = require 'fs'` to the top of the file where you're declaring the external modules/packages being used.
3. Add the readFile function call to the init method and then populate the clipboard, and call appendFile whenever you copy something so that it's stored in the file. (Alternately there might be a shutdown or close method by Atom, and you could just copy the entire contents of the clipboard when this is called.)

**Comment by reachspirit** [comment]
Thanks for the suggestion! I have managed to preserve the data with serialize method. Not in a standard way, but it's simple and effective.
