### ISSUE TITLE
Experiment Setup

### ISSUE THREAD

**Issue by arjunmadan** [cleebp/csc-510-group-g#55]
- Finalize design and structure of the experiment.

**Comment by cleebp** [comment]
I just created another google document and shared it with everyone called "Experiment Check Sheet". The idea is that we will each print out one of these per experiment and take notes on the experiment to be conducted.

Right now it just has basic information like subject's name, date, start/end time, which experiment is being conducted, etc. But it can be expanded to also include the check sheet for each of the tasks we will perform during the experiment.

**Comment by cleebp** [comment]
Okay so we have decided that the goal of each experiment will be to take a pretty empty project from the "clipboard-history" package, and eventually through a series of tasks build the final working "clipboard-history" package. Tasks will be designed to test specific things like copy/paste across windows, inside the same window, from outside sources, etc. so that we have a range of data points.

ALSO for each task we will build a spreadsheet detailing these metrics for that task so that we can come up with cool stats:
- Time to completion
- # windows switched between
- Errors?

By getting these stats we can then come up with some sort of ranking algorithm that will give us a concrete score for each package that will essentially tell us which was best (to answer that question). We will also have specific post surveys for each package so we can back up this score with user experiences.

**Comment by cleebp** [comment]
So my gigantic slew of assignments has finally slowed down and I should be able to get a ton of work done on this tonight and tomorrow AM, I'll start with taking the code base and breaking it apart into different source files and commenting the lines we want them to look for in their tasks. I'll put this in a new folder on the github so we all have access to it :D
