### ISSUE TITLE
Data collected from experiments

### ISSUE THREAD

**Issue by arjunmadan** [cleebp/csc-510-group-g#73]
I've added the start and end times, and calculated the duration for each of the tasks (page 2 on the google sheets thingamajig). I've also left a template for the second set of experiments.

**Comment by cleebp** [comment]
Cool looks good, I'll add my data after all my experiments are done, one question though.

On the second sheets you have total times that are different than the first sheet?

For my data since its being done with a stopwatch I only have the total time like yours on the second sheet (where timing is only done once they start the task, it doesn't include reading time).

**Comment by arjunmadan** [comment]
Yeah I filled up the first sheet and then realised it included the reading
time and that shouldn't really be included as part of the task. I was just
too lazy to remove it. :P

**Comment by cleebp** [comment]
Haha okay
